version: '3'
services:
  mysql_devdb:
    image: mysql:8.0
    container_name: mysql_devdb
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: kiosk
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  mysql_testdb:
    image: mysql:8.0
    container_name: mysql_testdb
    ports:
      - 3307:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: kiosk
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
