package team04.kioskbe;

import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public class MockController {

    @GetMapping("/mock/index")
    public String index() {
        return "{\n"
                + "  \"categories\": [\n"
                + "    {\n"
                + "      \"id\": \"coffee\",\n"
                + "      \"name\": \"커피\"\n"
                + "    },\n"
                + "    {\n"
                + "      \"id\": \"latte\",\n"
                + "      \"name\": \"라떼\"\n"
                + "    },\n"
                + "    {\n"
                + "      \"id\": \"tea\",\n"
                + "      \"name\": \"티\"\n"
                + "    },\n"
                + "    {\n"
                + "      \"id\": \"juice\",\n"
                + "      \"name\": \"주스\"\n"
                + "    },\n"
                + "    {\n"
                + "      \"id\": \"decaffeine\",\n"
                + "      \"name\": \"디카페인\"\n"
                + "    }\n"
                + "  ],\n"
                + "  \"coffee\": [\n"
                + "    {\n"
                + "      \"id\": 1,\n"
                + "      \"type\": \"coffee\",\n"
                + "      \"name\": \"아메리카노\",\n"
                + "      \"img\": \"https://image/americano.jpg\",\n"
                + "      \"price\": 4000,\n"
                + "      \"options\": {\n"
                + "        \"size\": [\n"
                + "          {\n"
                + "            \"id\": 1,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"big\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"id\": 2,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"medium\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"id\": 3,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"small\"\n"
                + "          }\n"
                + "        ],\n"
                + "        \"temperature\": [\n"
                + "          {\n"
                + "            \"id\": 4,\n"
                + "            \"type\": \"온도\",\n"
                + "            \"value\": \"hot\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"id\": 5,\n"
                + "            \"type\": \"온도\",\n"
                + "            \"value\": \"cold\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    },\n"
                + "    {\n"
                + "      \"id\": 2,\n"
                + "      \"type\": \"coffee\",\n"
                + "      \"name\": \"콜드브루\",\n"
                + "      \"img\": \"https://image/coldbrew.jpg\",\n"
                + "      \"price\": 5000,\n"
                + "      \"options\": {\n"
                + "        \"size\": [\n"
                + "          {\n"
                + "            \"id\": 1,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"big\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"id\": 2,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"medium\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"id\": 3,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"small\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    }\n"
                + "  ]\n"
                + "}";
    }


    @GetMapping("/mock/drinks?category=coffee")
    public String drinks() {
        return "[\n"
                + "  {\n"
                + "    \"id\": 1,\n"
                + "    \"type\": \"coffee\",\n"
                + "    \"name\": \"아메리카노\",\n"
                + "    \"img\": \"https://image/americano.jpg\",\n"
                + "    \"price\": 4000,\n"
                + "    \"options\": {\n"
                + "      \"size\": [\n"
                + "        {\n"
                + "          \"id\": 1,\n"
                + "          \"type\": \"사이즈\",\n"
                + "          \"value\": \"big\"\n"
                + "        },\n"
                + "        {\n"
                + "          \"id\": 2,\n"
                + "          \"type\": \"사이즈\",\n"
                + "          \"value\": \"medium\"\n"
                + "        },\n"
                + "        {\n"
                + "          \"id\": 3,\n"
                + "          \"type\": \"사이즈\",\n"
                + "          \"value\": \"small\"\n"
                + "        }\n"
                + "      ],\n"
                + "      \"temperature\": [\n"
                + "        {\n"
                + "          \"id\": 4,\n"
                + "          \"type\": \"온도\",\n"
                + "          \"value\": \"hot\"\n"
                + "        },\n"
                + "        {\n"
                + "          \"id\": 5,\n"
                + "          \"type\": \"온도\",\n"
                + "          \"value\": \"cold\"\n"
                + "        }\n"
                + "      ]\n"
                + "    }\n"
                + "  },\n"
                + "  {\n"
                + "    \"id\": 2,\n"
                + "    \"type\": \"coffee\",\n"
                + "    \"name\": \"콜드브루\",\n"
                + "    \"img\": \"https://image/coldbrew.jpg\",\n"
                + "    \"price\": 5000,\n"
                + "    \"options\": {\n"
                + "      \"size\": [\n"
                + "        {\n"
                + "          \"id\": 1,\n"
                + "          \"type\": \"사이즈\",\n"
                + "          \"value\": \"big\"\n"
                + "        },\n"
                + "        {\n"
                + "          \"id\": 2,\n"
                + "          \"type\": \"사이즈\",\n"
                + "          \"value\": \"medium\"\n"
                + "        },\n"
                + "        {\n"
                + "          \"id\": 3,\n"
                + "          \"type\": \"사이즈\",\n"
                + "          \"value\": \"small\"\n"
                + "        }\n"
                + "      ]\n"
                + "    }\n"
                + "  }\n"
                + "]";
    }


    @GetMapping("/mock/orders")
    public String orders() {
        return "[\n"
                + "  {\n"
                + "    \"order_id\": 1,\n"
                + "    \"total_price\": 17000,\n"
                + "    \"received_amount\": 17000,\n"
                + "    \"drinks\": [\n"
                + "      {\n"
                + "        \"drink_id\": 1,\n"
                + "        \"drink_name\": \"아메리카노\",\n"
                + "        \"quantity\": 3,\n"
                + "        \"option_list\": [\n"
                + "          {\n"
                + "            \"id\": 1,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"big\"\n"
                + "          },\n"
                + "          {\n"
                + "            \"id\": 5,\n"
                + "            \"type\": \"온도\",\n"
                + "            \"value\": \"cold\"\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"drink_id\": 2,\n"
                + "        \"drink_name\": \"콜드브루\",\n"
                + "        \"quantity\": 1,\n"
                + "        \"option_list\": [\n"
                + "          {\n"
                + "            \"id\": 2,\n"
                + "            \"type\": \"사이즈\",\n"
                + "            \"value\": \"medium\"\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ]\n"
                + "  }\n"
                + "]";
    }

    @GetMapping("/mock/payments")
    public String payments() {
        return "[\n"
                + "  {\n"
                + "    \"type\": \"card\",\n"
                + "    \"img\": \"https://image/card.jpg\",\n"
                + "    \"link\": \"/orders?type=card\"\n"
                + "  },\n"
                + "  {\n"
                + "    \"type\": \"cash\",\n"
                + "    \"img\": \"https://image/cash.jpg\",\n"
                + "    \"link\": \"/orders?type=cash\"\n"
                + "  }\n"
                + "]";
    }
}
